<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AdSlotConfig;

class AdSlotConfigSeeder extends Seeder
{
    public function run(): void
    {
        $slots = [
            [
                'placement' => 'home_hero',
                'label' => 'Beranda Atas (Hero Slide)',
                'description' => 'Slider utama di halaman beranda, rasio landscape lebar.',
                'width' => 1200,
                'height' => 400,
                'min_width' => 1200,
                'min_height' => 400,
                'max_width' => 2400,
                'max_height' => 800,
                'aspect_ratio' => '3:1',
                'aspect_tolerance' => 0.05,
                'allowed_extensions' => ['jpg','jpeg','png','webp'],
                'allowed_mimes' => ['image/jpeg','image/png','image/webp'],
                'max_file_size_kb' => 2048,
                'is_strict_dimension' => false,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'placement' => 'landing_mid',
                'label' => 'Landing Page Tengah (Di antara Section)',
                'description' => 'Banner horizontal di tengah landing page.',
                'width' => 1200,
                'height' => 400,
                'min_width' => 1000,
                'min_height' => 300,
                'max_width' => 2400,
                'max_height' => 900,
                'aspect_ratio' => '3:1',
                'aspect_tolerance' => 0.08,
                'allowed_extensions' => ['jpg','jpeg','png','webp'],
                'allowed_mimes' => ['image/jpeg','image/png','image/webp'],
                'max_file_size_kb' => 2048,
                'is_strict_dimension' => false,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'placement' => 'catalog_top',
                'label' => 'Atas Halaman Katalog / Cari Hunian',
                'description' => 'Banner atas katalog, landscape sedang.',
                'width' => 1200,
                'height' => 300,
                'min_width' => 1000,
                'min_height' => 250,
                'max_width' => 2000,
                'max_height' => 600,
                'aspect_ratio' => '4:1',
                'aspect_tolerance' => 0.08,
                'allowed_extensions' => ['jpg','jpeg','png','webp'],
                'allowed_mimes' => ['image/jpeg','image/png','image/webp'],
                'max_file_size_kb' => 1536,
                'is_strict_dimension' => false,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'placement' => 'search_sidebar',
                'label' => 'Sidebar Halaman Pencarian',
                'description' => 'Banner vertikal di sidebar, rasio portrait.',
                'width' => 300,
                'height' => 600,
                'min_width' => 300,
                'min_height' => 600,
                'max_width' => 600,
                'max_height' => 1200,
                'aspect_ratio' => '1:2',
                'aspect_tolerance' => 0.05,
                'allowed_extensions' => ['jpg','jpeg','png','webp'],
                'allowed_mimes' => ['image/jpeg','image/png','image/webp'],
                'max_file_size_kb' => 1536,
                'is_strict_dimension' => false,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'placement' => 'catalog_in_feed',
                'label' => 'Di Antara Grid Daftar Kost (Feed Ad)',
                'description' => 'Iklan square di sela grid kost.',
                'width' => 1080,
                'height' => 1080,
                'min_width' => 600,
                'min_height' => 600,
                'max_width' => 1200,
                'max_height' => 1200,
                'aspect_ratio' => '1:1',
                'aspect_tolerance' => 0.05,
                'allowed_extensions' => ['jpg','jpeg','png'],
                'allowed_mimes' => ['image/jpeg','image/png'],
                'max_file_size_kb' => 1024,
                'is_strict_dimension' => false,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'placement' => 'footer_banner',
                'label' => 'Banner Di Atas Footer',
                'description' => 'Banner tipis di atas footer, sangat lebar.',
                'width' => 1200,
                'height' => 200,
                'min_width' => 1000,
                'min_height' => 150,
                'max_width' => 2400,
                'max_height' => 500,
                'aspect_ratio' => '6:1',
                'aspect_tolerance' => 0.10,
                'allowed_extensions' => ['jpg','jpeg','png','webp'],
                'allowed_mimes' => ['image/jpeg','image/png','image/webp'],
                'max_file_size_kb' => 1024,
                'is_strict_dimension' => false,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'placement' => 'custom',
                'label' => 'Lokasi Kustom Lainnya',
                'description' => 'Untuk penempatan custom, toleransi longgar.',
                'width' => 800,
                'height' => 600,
                'min_width' => 400,
                'min_height' => 300,
                'max_width' => 2000,
                'max_height' => 2000,
                'aspect_ratio' => '4:3',
                'aspect_tolerance' => 0.15,
                'allowed_extensions' => ['jpg','jpeg','png','webp'],
                'allowed_mimes' => ['image/jpeg','image/png','image/webp'],
                'max_file_size_kb' => 2048,
                'is_strict_dimension' => false,
                'is_active' => true,
                'sort_order' => 99,
            ],
        ];

        foreach ($slots as $slot) {
            AdSlotConfig::updateOrCreate(
                ['placement' => $slot['placement']],
                $slot
            );
        }
    }
}
